In [2]:
import random
def generate_random_number():
    #Generate  a random number between 1 and 10
    random_number = random.randint(1, 10)
    return random_number
#Call the function and print the result
random_result = generate_random_number()
print(f"Random Number: {random_result}")

Random Number: 9


Shows in an array the numbers ordered from the most to the least repeated of a matrix in python

In [13]:
from collections import Counter

def most_to_least_repeated(matrix):
    #Flatten the matrix into a list
    flattened_list = [num for row in matrix for num in row]
    
    #Count the occurrences of each number
    count_dict = Counter(flattened_list)
    
    #Sort the numbers based on their frequency in descending order
    sorted_numbers = sorted(count_dict, key=lambda x: count_dict[x], reverse=True)
    return sorted_numbers
#example matrix
example_matrix = [
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]
]
#get the sorted numbers based on frequency
sorted_numbers = most_to_least_repeated(example_matrix)

#Print the result
print("Numbers ordered from most to least repeated: ",sorted_numbers)

Numbers ordered from most to least repeated:  [1, 2, 3, 4]


Bubble Sort

In [2]:
# Bubble Sort
import random
def bubbleSort(array):
    for i in range(len(array)):
        #loop to compare array elements
        for j in range(len(array) -i -1):
            #compare two adjacent elements
            #compare > to < to sort in descending order
            if array[j] > array[j+i]:
                #swapping elements if they are not in the correct order
                temp = array[j]
                array[j] = array[j+1]
                array[j+1] = temp
#test
array = random.sample(range(0,100),50)
print("Given array is: ")
print(array)

bubbleSort(array)

print('The array after sorting with Bubble Sort: ')
print(array)

print('The array after sorting with Bubble Sort: ')
print(array)

#Optimized Bubble Sort
def bubbleSort_opt(array):
    for i in range(len(array)):
        num_swaps = 0
        #loop to compare array elements
        for j in range(len(array) -i -1):
            #compare two adjacent elements
            #change > to < to sort in descending order
            if array[j] > array[j+1]:
                #swapping elements if they are not in the intended order
                temp = array[j]
                array[j] = array[j+1]
                array[j+1] = temp
                #increment num_swaps
                num_swaps = num_swaps+1
        if num_swaps == 0:
            return
#test
array = random.sample(range(0,100),50)
print("Given array is: ")
print(array)

bubbleSort_opt(array)
print('The array after sorting with (optimized) Bubble Sort: ')
print(array)

Given array is: 
[24, 2, 29, 92, 36, 56, 10, 22, 75, 1, 97, 94, 55, 50, 60, 49, 90, 89, 40, 21, 81, 0, 46, 88, 20, 27, 69, 73, 32, 82, 57, 72, 93, 8, 37, 4, 39, 61, 47, 65, 95, 25, 78, 33, 52, 9, 31, 84, 51, 30]
The array after sorting with Bubble Sort: 
[2, 1, 10, 0, 24, 22, 21, 29, 8, 20, 36, 27, 50, 46, 55, 60, 73, 4, 49, 56, 32, 40, 37, 39, 57, 75, 82, 81, 47, 69, 65, 88, 61, 25, 89, 33, 9, 92, 72, 93, 90, 31, 52, 95, 94, 78, 84, 51, 97, 30]
The array after sorting with Bubble Sort: 
[2, 1, 10, 0, 24, 22, 21, 29, 8, 20, 36, 27, 50, 46, 55, 60, 73, 4, 49, 56, 32, 40, 37, 39, 57, 75, 82, 81, 47, 69, 65, 88, 61, 25, 89, 33, 9, 92, 72, 93, 90, 31, 52, 95, 94, 78, 84, 51, 97, 30]
Given array is: 
[92, 4, 94, 85, 7, 27, 29, 70, 50, 39, 56, 34, 8, 59, 86, 44, 22, 60, 42, 62, 83, 1, 3, 98, 55, 41, 43, 9, 12, 90, 15, 84, 71, 57, 49, 75, 81, 23, 96, 38, 65, 58, 5, 19, 66, 47, 91, 25, 37, 54]
The array after sorting with (optimized) Bubble Sort: 
[1, 3, 4, 5, 7, 8, 9, 12, 15, 19, 22, 23, 25, 

Example new 2 

In [7]:
import random

# Generate a random number between 1 and 10
random_number = random.randint(1, 10)

print("Random number:", random_number)

Random number: 1


Example new 3

In [4]:
import numpy as np

# Create a NumPy array
array1 = np.array([1, 2, 3, 4, 5])

# Perform basic operations on the array
array2 = array1 * 2
array3 = array1 + array2

# Calculate the mean and standard deviation of the array
mean_value = np.mean(array1)
std_dev = np.std(array1)

# Display the results
print("Original Array:", array1)
print("Array after multiplication:", array2)
print("Array after addition:", array3)
print("Mean:", mean_value)
print("Standard Deviation:", std_dev)

Original Array: [1 2 3 4 5]
Array after multiplication: [ 2  4  6  8 10]
Array after addition: [ 3  6  9 12 15]
Mean: 3.0
Standard Deviation: 1.4142135623730951


Example new 4

In [8]:
import random

random_float = random.random()
print("Random float between 0 and 1:", random_float)

Random float between 0 and 1: 0.7158570619810933


Example new 5

In [5]:
import numpy as np

#Create two matrices
matrix1 = np.array([[1,2], [3,4]])
matrix2 = np.array([[5,6], [7,8]])

#Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("Matrix 2:")
print(matrix2)

print("\nResult of Matrix Multiplication:")
print(result)

Matrix 1:
[[1 2]
 [3 4]]
Matrix 2:
[[5 6]
 [7 8]]

Result of Matrix Multiplication:
[[19 22]
 [43 50]]


Example New 6

In [9]:
import random

random_int_range = random.randint(20,50)
print("Random integer between 20 and 50: ", random_int_range)

Random integer between 20 and 50:  31


Example New 7

In [6]:
import numpy as np

#Generate an array of random numbers
random_numbers = np.random.rand(3,3)

print("Random Numbers:")
print(random_numbers)

Random Numbers:
[[0.08815338 0.48957245 0.49810905]
 [0.33174853 0.96825216 0.43746005]
 [0.41263338 0.62286452 0.51306564]]


Example New 8

In [10]:
import random

my_list = [1,2,3,4,5]
random.shuffle(my_list)
print("Shuffled list: ", my_list)

Shuffled list:  [1, 5, 2, 3, 4]


Example New 9

In [12]:
import random
fruits = ["apple", "banana", "orange", "grape","kiwi"]
random_fruit = random.choice(fruits)
print("Randomly chosen fruit: ", random_fruit)

Randomly chosen fruit:  apple
